# Generated by Django 2.2.16 on 2020-10-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.TextField(max_length=30, null=True)),
                ('dob', models.DateField()),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studapp.major'),
        ),
    ]
